{
 "title": "netology",
 "time": { "from": "2021-11-02T22:31:21.294Z", "to": "2021-11-03T22:31:21.294Z" },
 "panels": [
  {
   "title": "CPU LA 15",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg (node_load15)/count(count(node_cpu_seconds_total)by(cpu))*100"
    }
   ]
  },
  {
   "title": "CPU la 5",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg (node_load5)/count(count(node_cpu_seconds_total)by(cpu))*100"
    }
   ]
  },
  {
   "title": "CPU LA 1",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg (node_load1)/count(count(node_cpu_seconds_total)by(cpu))*100"
    }
   ]
  },
  {
   "title": "usage mem",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes-node_memory_MemFree_bytes)/(node_memory_MemTotal_bytes))*100"
    }
   ]
  },
  {
   "title": "disk usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100-((node_filesystem_avail_bytes*100)/node_filesystem_size_bytes)"
    }
   ]
  },
  {
   "title": "CPU utilization",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1-avg by (instance) (irate(node_cpu_seconds_total{mode='idle'}[1m])))"
    }
   ]
  }
 ]
}